export const keymap = [
  { path: 'w', icon: '☀️', title: 'weather' },
  { path: 'wp', icon: '⛅', title: 'partly sunny' },
  { path: 'ws', icon: '☀️', title: 'sunny' },
  { path: 'wr', icon: '☔', title: 'rainy' },
  { path: 'wc', icon: '☁️', title: 'cloudy' },
  { path: 'wi', icon: '❄️', title: 'snowflake' },
  { path: 'ww', icon: '⛄', title: 'snowman' },
  { path: 'wl', icon: '⚡', title: 'lightning' },
  { path: 'wb', icon: '🌀', title: 'cyclone' },
  { path: 'wf', icon: '🌁', title: 'foggy' },
  { path: 'a', icon: '🐰', title: 'animal' },
  { path: 'am', icon: '🐶', title: 'mamals' },
  { path: 'amc', icon: '🐆', title: 'cat' },
  { path: 'amch', icon: '🐈', title: 'housecat' },
  { path: 'amcl', icon: '🐆', title: 'leopard' },
  { path: 'amct', icon: '🐯', title: 'tiger' },
  { path: 'amd', icon: '🐶', title: 'dog' },
  { path: 'amdb', icon: '🐶', title: 'boxer' },
  { path: 'amdp', icon: '🐩', title: 'poodle' },
  { path: 'amsd', icon: '🐬', title: 'dolphin' },
  { path: 'ar', icon: '🐊', title: 'reptile' },
  { path: 'arf', icon: '🐸', title: 'frog' },
  { path: 'arc', icon: '🐊', title: 'crocodile' },
  { path: 'ard', icon: '🐉', title: 'dragon' }

  /*,
  { path: 'amm', icon: '🐭', title: 'mouse' },
  { path: 'amh', icon: '🐹', title: 'hamster' },
  { path: 'amr', icon: '🐰', title: 'rabbit' },
  { path: 'amw', icon: '🐺', title: 'wolf' },
  { path: 'aqq', icon: '🐨', title: 'koala' },
  { path: 'aqq', icon: '🐻', title: 'bear' },
  { path: 'aqq', icon: '🐷', title: 'pig' },
  { path: 'aqq', icon: '🐽', title: 'pig_nose' },
  { path: 'aqq', icon: '🐮', title: 'cow' },
  { path: 'aqq', icon: '🐗', title: 'boar' },
  { path: 'aqq', icon: '🐵', title: 'monkey_face' },
  { path: 'aqq', icon: '🐒', title: 'monkey' },
  { path: 'aqq', icon: '🐴', title: 'horse' },
  { path: 'aqq', icon: '🐎', title: 'racehorse' },
  { path: 'aqq', icon: '🐫', title: 'camel' },
  { path: 'aqq', icon: '🐑', title: 'sheep' },
  { path: 'aqq', icon: '🐘', title: 'elephant' },
  { path: 'aqq', icon: '🐼', title: 'panda_face' },
  { path: 'aqq', icon: '🐍', title: 'snake' },
  { path: 'aqq', icon: '🐦', title: 'bird' },
  { path: 'aqq', icon: '🐤', title: 'baby_chick' },
  { path: 'aqq', icon: '🐥', title: 'hatched_chick' },
  { path: 'aqq', icon: '🐣', title: 'hatching_chick' },
  { path: 'aqq', icon: '🐔', title: 'chicken' },
  { path: 'aqq', icon: '🐧', title: 'penguin' },
  { path: 'aqq', icon: '🐢', title: 'turtle' },
  { path: 'aqq', icon: '🐛', title: 'bug' },
  { path: 'aqq', icon: '🐝', title: 'honeybee' },
  { path: 'aqq', icon: '🐜', title: 'ant' },
  { path: 'aqq', icon: '🐞', title: 'beetle' },
  { path: 'aqq', icon: '🐌', title: 'snail' },
  { path: 'aqq', icon: '🐙', title: 'octopus' },
  { path: 'aqq', icon: '🐠', title: 'tropical_fish' },
  { path: 'aqq', icon: '🐟', title: 'fish' },
  { path: 'aqq', icon: '🐳', title: 'whale' },
  { path: 'aqq', icon: '🐋', title: 'whale2' },
  { path: 'aqq', icon: '🐬', title: 'dolphin' },
  { path: 'aqq', icon: '🐄', title: 'cow2' },
  { path: 'aqq', icon: '🐏', title: 'ram' },
  { path: 'aqq', icon: '🐀', title: 'rat' },
  { path: 'aqq', icon: '🐃', title: 'water_buffalo' },
  { path: 'aqq', icon: '🐅', title: 'tiger2' },
  { path: 'aqq', icon: '🐇', title: 'rabbit2' },
  { path: 'aqq', icon: '🐐', title: 'goat' },
  { path: 'aqq', icon: '🐓', title: 'rooster' },
  { path: 'aqq', icon: '🐕', title: 'dog2' },
  { path: 'aqq', icon: '🐖', title: 'pig2' },
  { path: 'aqq', icon: '🐁', title: 'mouse2' },
  { path: 'aqq', icon: '🐂', title: 'ox' },
  { path: 'aqq', icon: '🐡', title: 'blowfish' },
  { path: 'qqq', icon: '🐾', title: 'paw_prints' },
  { path: 'qqq', icon: '💐', title: 'bouquet' },
  { path: 'qqq', icon: '🌸', title: 'cherry_blossom' },
  { path: 'qqq', icon: '🌷', title: 'tulip' },
  { path: 'qqq', icon: '🍀', title: 'four_leaf_clover' },
  { path: 'qqq', icon: '🌹', title: 'rose' },
  { path: 'qqq', icon: '🌻', title: 'sunflower' },
  { path: 'qqq', icon: '🌺', title: 'hibiscus' },
  { path: 'qqq', icon: '🍁', title: 'maple_leaf' },
  { path: 'qqq', icon: '🍃', title: 'leaves' },
  { path: 'qqq', icon: '🍂', title: 'fallen_leaf' },
  { path: 'qqq', icon: '🌿', title: 'herb' },
  { path: 'qqq', icon: '🍄', title: 'mushroom' },
  { path: 'qqq', icon: '🌵', title: 'cactus' },
  { path: 'qqq', icon: '🌴', title: 'palm_tree' },
  { path: 'qqq', icon: '🌲', title: 'evergreen_tree' },
  { path: 'qqq', icon: '🌳', title: 'deciduous_tree' },
  { path: 'qqq', icon: '🌰', title: 'chestnut' },
  { path: 'qqq', icon: '🌱', title: 'seedling' },
  { path: 'qqq', icon: '🌼', title: 'blossom' },
  { path: 'qqq', icon: '🌾', title: 'ear_of_rice' },
  { path: 'qqq', icon: '🐚', title: 'shell' },
  { path: 'qqq', icon: '🌐', title: 'globe_with_meridians' },
  { path: 'qqq', icon: '🌞', title: 'sun_with_face' },
  { path: 'qqq', icon: '🌝', title: 'full_moon_with_face' },
  { path: 'qqq', icon: '🌚', title: 'new_moon_with_face' },
  { path: 'qqq', icon: '🌑', title: 'new_moon' },
  { path: 'qqq', icon: '🌒', title: 'waxing_crescent_moon' },
  { path: 'qqq', icon: '🌓', title: 'first_quarter_moon' },
  { path: 'qqq', icon: '🌔', title: 'waxing_gibbous_moon' },
  { path: 'qqq', icon: '🌕', title: 'full_moon' },
  { path: 'qqq', icon: '🌖', title: 'waning_gibbous_moon' },
  { path: 'qqq', icon: '🌗', title: 'last_quarter_moon' },
  { path: 'qqq', icon: '🌘', title: 'waning_crescent_moon' },
  { path: 'qqq', icon: '🌜', title: 'last_quarter_moon_with_face' },
  { path: 'qqq', icon: '🌛', title: 'first_quarter_moon_with_face' },
  { path: 'qqq', icon: '🌔', title: 'moon' },
  { path: 'qqq', icon: '🌍', title: 'earth_africa' },
  { path: 'qqq', icon: '🌎', title: 'earth_americas' },
  { path: 'qqq', icon: '🌏', title: 'earth_asia' },
  { path: 'qqq', icon: '🌋', title: 'volcano' },
  { path: 'qqq', icon: '🌌', title: 'milky_way' },
  { path: 'qqq', icon: '🌊', title: 'ocean' },
  */
].sort((a, b) => a.path.length - b.path.length)

export const keyTree = {}

for (const { path, ...value } of keymap) {
  setKey(value, path)
}

function setKey (value, path, parent = keyTree) {
  const seg = Array.isArray(path) ? path : path.split('')
  const [key, ...subkey] = seg
  if (subkey.length === 0) {
    parent.keys = parent.keys || {}
    parent.keys[key] = value
  } else {
    parent.keys = parent.keys || {}
    parent.keys[key] = parent.keys[key] || {}
    setKey (value, subkey, parent.keys[key])
  }
}
